language: python
python:
  - "2.7"
before_script:
  - sudo apt-get update
  - sudo apt-get install -y openssl build-essential xorg libssl-dev libxrender-dev wget xvfb fontconfig cabextract xfonts-75dpi
  - wget https://s3-ap-southeast-1.amazonaws.com/uploads-ap.hipchat.com/37228/731420/xaWQsEMSblrNsjt/wkhtmltox-0.12.2.1_linux-trusty-amd64.deb
  - sudo dpkg -i wkhtmltox-0.12.2.1_linux-trusty-amd64.deb
install:
  - CFLAGS=-O0 pip install lxml
  - pip install flake8
  - python setup.py install
script:
  - python setup.py test
  - flake8 .
notifications:
  email:
    - ci-notify@openlabs.co.in
